/**
 * Zuordnung der bisherigen Font-Awesome-Namen zu Lucide-Icons.
 *
 * Das Design-System v2 zeichnet Icons im Lucide-Stil (Outline, 24-px-Raster,
 * stroke-width 1.75). Die alten Namen bleiben als Schlüssel, damit Daten wie
 * `icon: 'fa-crop'` in Composables unverändert weiter funktionieren.
 */
import {
  ALargeSmall,
  ArrowDown,
  ArrowLeftRight,
  ArrowRight,
  ArrowUp,
  AudioWaveform,
  Ban,
  Bold,
  BookOpen,
  Calendar,
  Check,
  ChevronDown,
  ChevronUp,
  Circle,
  CircleAlert,
  CircleCheck,
  CircleHelp,
  CirclePlay,
  CirclePlus,
  Clipboard,
  Clock,
  Cloud,
  CloudUpload,
  Code,
  Coffee,
  Columns2,
  Contrast,
  Copy,
  Crop,
  Crosshair,
  Database,
  Download,
  Expand,
  Eye,
  EyeOff,
  File,
  FileArchive,
  FileImage,
  FileInput,
  FileOutput,
  FolderOpen,
  Frame,
  Gauge,
  Grid2x2,
  Grid3x3,
  Group,
  Hand,
  History,
  House,
  Image,
  Images,
  Info,
  Italic,
  Keyboard,
  Languages,
  Laptop,
  Layers,
  LayoutGrid,
  Lightbulb,
  Link,
  List,
  ListChecks,
  LoaderCircle,
  Maximize2,
  Menu,
  Minimize2,
  Moon,
  MousePointer2,
  Move,
  MoveHorizontal,
  MoveVertical,
  PaintBucket,
  Paintbrush,
  Palette,
  Pen,
  Pencil,
  Pipette,
  Play,
  Plus,
  Pointer,
  Printer,
  Redo2,
  RefreshCw,
  Rocket,
  Ruler,
  Save,
  Settings,
  Shield,
  Shrink,
  SlidersHorizontal,
  Smartphone,
  Square,
  SquareCheck,
  SquareDashed,
  Sun,
  TextCursor,
  Trash2,
  TriangleAlert,
  Tv,
  Type,
  Undo2,
  Upload,
  UserX,
  WandSparkles,
  Wifi,
  X,
  Zap,
  ZoomIn,
} from 'lucide-vue-next';

export const iconMap = {
  adjust: Contrast,
  'arrow-down': ArrowDown,
  'arrow-right': ArrowRight,
  'arrow-up': ArrowUp,
  'arrows-alt': Move,
  'arrows-alt-h': MoveHorizontal,
  'arrows-alt-v': MoveVertical,
  ban: Ban,
  bars: Menu,
  bold: Bold,
  bolt: Zap,
  'book-open': BookOpen,
  'border-all': Grid2x2,
  'border-style': SquareDashed,
  calendar: Calendar,
  check: Check,
  'check-circle': CircleCheck,
  'check-square': SquareCheck,
  'chess-board': Grid3x3,
  'chevron-down': ChevronDown,
  'chevron-up': ChevronUp,
  circle: Circle,
  'circle-half-stroke': Contrast,
  clipboard: Clipboard,
  clock: Clock,
  clone: Copy,
  cloud: Cloud,
  'cloud-upload-alt': CloudUpload,
  code: Code,
  coffee: Coffee,
  cog: Settings,
  columns: Columns2,
  compress: Shrink,
  'compress-arrows-alt': Minimize2,
  copy: Copy,
  crop: Crop,
  'crop-alt': Crop,
  crosshairs: Crosshair,
  database: Database,
  download: Download,
  edit: Pencil,
  'exchange-alt': ArrowLeftRight,
  'exclamation-circle': CircleAlert,
  'exclamation-triangle': TriangleAlert,
  expand: Expand,
  'expand-arrows-alt': Maximize2,
  eye: Eye,
  'eye-dropper': Pipette,
  'eye-slash': EyeOff,
  file: File,
  'file-archive': FileArchive,
  'file-export': FileOutput,
  'file-image': FileImage,
  'file-import': FileInput,
  'fill-drip': PaintBucket,
  'folder-open': FolderOpen,
  font: Type,
  'hand-paper': Hand,
  'hand-point-up': Pointer,
  'hand-pointer': Pointer,
  history: History,
  home: House,
  'i-cursor': TextCursor,
  image: Image,
  images: Images,
  'info-circle': Info,
  italic: Italic,
  keyboard: Keyboard,
  language: Languages,
  laptop: Laptop,
  'layer-group': Layers,
  lightbulb: Lightbulb,
  link: Link,
  list: List,
  magic: WandSparkles,
  'mobile-alt': Smartphone,
  moon: Moon,
  'mouse-pointer': MousePointer2,
  'object-group': Group,
  'paint-brush': Paintbrush,
  palette: Palette,
  pen: Pen,
  play: Play,
  'play-circle': CirclePlay,
  plus: Plus,
  'plus-circle': CirclePlus,
  print: Printer,
  'question-circle': CircleHelp,
  redo: Redo2,
  rocket: Rocket,
  'ruler-combined': Ruler,
  save: Save,
  'search-plus': ZoomIn,
  'shield-alt': Shield,
  'sliders-h': SlidersHorizontal,
  spinner: LoaderCircle,
  square: Square,
  sun: Sun,
  sync: RefreshCw,
  'sync-alt': RefreshCw,
  'tachometer-alt': Gauge,
  tasks: ListChecks,
  'text-height': ALargeSmall,
  th: Grid3x3,
  'th-large': LayoutGrid,
  'th-list': List,
  times: X,
  trash: Trash2,
  'trash-alt': Trash2,
  tv: Tv,
  undo: Undo2,
  upload: Upload,
  'user-slash': UserX,
  'vector-square': Frame,
  vuejs: Code,
  'wave-square': AudioWaveform,
  wifi: Wifi,
};

/**
 * Normalisiert 'fas fa-crop', 'fa-crop' oder 'crop' auf den Schlüssel 'crop'.
 * Modifikatoren wie 'fa-spin' oder 'fa-fw' werden ignoriert.
 * @param {string} raw
 * @returns {{ key: string, spin: boolean }}
 */
export function parseIconName(raw) {
  const parts = String(raw || '')
    .split(/\s+/)
    .filter(Boolean);
  let key = '';
  let spin = false;
  for (const part of parts) {
    if (part === 'fa-spin') {
      spin = true;
      continue;
    }
    if (['fas', 'far', 'fab', 'fa', 'fa-fw', 'fa-solid', 'fa-regular'].includes(part)) continue;
    key = part.replace(/^fa-/, '');
  }
  return { key, spin };
}
